name: pdfrx_fork
description: A clone version of pdfrx package with some additional features and bug fixes supporting for Flutter < 3.19.
version: 0.0.1
repository: https://github.com/duynguyen250399/pdfrx_fork

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  collection: ^1.17.2
  crypto: ^3.0.3
  ffi: ^2.1.0
  flutter:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.18.1
  path: ^1.8.3
  path_provider: ^2.1.2
  rxdart: ^0.27.7
  synchronized: ^3.1.0+1
  url_launcher: ^6.2.4
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true
